---
abstract: 'Dancer session store backed by a Catmandu::Store'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-Catmandu
provides:
  Dancer::Session::Catmandu:
    file: lib/Dancer/Session/Catmandu.pm
    version: 0.02
requires:
  Catmandu: 0.03
  Dancer: 1.3
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
